import { translate } from "~/i18n";

export const languages = [
  { name: 'text/plain', filePattern:null, title:translate('plainText') },
  { name: 'html', filePattern:'\\.html', title:'HTML' },
  { name: 'xml', filePattern:'\\.(xml|svg)', contentPattern: '<\\?xml', title:'XML' },
  { name: 'css', filePattern:'\\.css', title:'CSS' },
  { name: 'javascript', filePattern:'\\.jsx?', title:'JavaScript/JSX' },
  { name: 'typescript', filePattern:'\\.tsx?', title:'TypeScript/TSX' },
  { name: 'c', filePattern:'\\.c', title:'C' },
  { name: 'cpp', filePattern:'\\.cpp', title:'C++' },
  { name: 'java', filePattern:'\\.java', title:'Java' },
  { name: 'json', filePattern:'\\.json', title:'JSON' },
  { name: 'yaml', filePattern:'\\.yml', title:'YAML' },
  { name: 'sql', filePattern:'\\.sql', title:'SQL' },
  { name: 'python', filePattern:'\\.py', title:'Python' },
  { name: 'rust', filePattern:'\\.rs', title:'Rust' },
  { name: 'php', filePattern:'\\.php', title:'PHP' },
  { name: 'lua', filePattern:'\\.lua', title:'Lua' },
  { name: 'csharp', filePattern:'\\.cs', title:'C#' },
  { name: 'razor', filePattern:'\\.(cshtml|razor)', title:'Razor C#' },
  { name: 'ini', filePattern:'\\.ini', title:'INI' },
  { name: 'markdown', filePattern:'\\.md', title:'Markdown' },
  { name: 'bat', filePattern:'\\.(bat|cmd)', title:'Batch' },
  { name: 'shell', filePattern:'\\.(bashrc|bash_history|bash_logout|bash_profile|profile|sh|zlogin|zlogout|zprofile|zsh|zshenv|zshrc)', title:'Shell Script' },
  { name: 'csv', filePattern:'\\.csv', title:'CSV' },
  { name: 'vb', filePattern:'\\.vb', title:'Visual Basic' },
  { name: 'vue', filePattern:'\\.vue', title:'Vue' },
  { name: 'svelte', filePattern:'\\.svelte', title:'Svelte' },
  { name: 'vim', filePattern:'\\.vim', title:'Vim' },
  { name: 'pug', filePattern:'\\.pug', title:'Pug' },
  { name: 'powershell', filePattern:'\\.ps', title:'PowerShell' },
  { name: 'handlebars', filePattern:'\\.hbs', title:'Handlebars' },
  { name: 'http', filePattern:'\\.http', title:'HTTP' },
  { name: 'toml', filePattern:'\\.toml', title:'TOML' },
  { name: 'go', filePattern:'\\.go', title:'Go' },
  { name: 'graphql', filePattern:'\\.gql', title:'GraphQL' },
  { name: 'ruby', filePattern:'\\.rb', title:'Ruby' },
  { name: 'kotlin', filePattern:'\\.kt', title:'Kotlin' },
  { name: 'dart', filePattern:'\\.dart', title:'Dart' },
  { name: 'scss', filePattern:'\\.s(c|a)ss', title:'SCSS' },
  { name: 'less', filePattern:'\\.less', title:'Less' },
];
languages.sort((a, b) => a.title.localeCompare(b.title));

export const defaultLanguage = 'text/plain';